version: '3.7'

services:
  runner:
    image: cronsample:latest
    environment:
      - JOB=HealthJob
      - TEST_ENDPOINT_BASE_URL=https://dev.to
    build:
      context: .
      dockerfile: CronSample/Dockerfile